### ISSUE TITLE
Create Mockup of Navbar and Slider HomePage

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/HotelCuellarWebPage#1]
https://demo.accesspressthemes.com/swing/city-hotel/ 
Considerations: 
- Replace Swing Logo for Hotel Cuellar Logo
- Translate "Contact us" to Spanish
- Remove Twitter and Youtube icons
- Navbar links: Inicio, Nosotros, Habitaciones, Servicios, Contacto, RESERVA AHORA
- Remove Card Icon and Hamburger Menu from navbar
- Create the full width slider and implement the *check-in* form from here http://preview.themeforest.net/item/countryholidays-country-hotel-and-bed-breakfast/full_screen_preview/11800971

-

**Comment by Inatedy** [comment]
![Inicio-1](https://user-images.githubusercontent.com/46948948/60750137-b515d480-9f69-11e9-8317-95c51f9cd563.png)
![Inicio-2](https://user-images.githubusercontent.com/46948948/60750138-b5ae6b00-9f69-11e9-8c7f-a8885c1b6f4b.png)
 Lo que me falto es la misma tipografia

**Comment by MartinMelo97** [comment]
Perfecto Indra! Me gusta mucho!
